### ISSUE TITLE
Task: Create sign up functionality.

### ISSUE THREAD

**Issue by IceCalves** [cse442-spring-2020-offering/cse442-semester-project-blood-donaters#28]
Acceptance Tests:

1. Go to sign up form.
2. Input and submit a new user.
3. Check to make sure that you are able to sign in to the new user.

**Comment by abdurrahman75** [comment]
Acceptance Test:

1) Click on the Sign Up button from the Navbar.

2) In the Sign Up page, Enter your first name, last name, email, password, blood group and medical history.

3) Click on the Sign Up button which will redirect to a page with a signup confirmation message or error message if any error happens.
